server:
  port: 9090
  servlet:
    context-path: /senlin-jiaoyi

spring:
  application:
    name: senlin-jiaoyi
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      location: ${multipart.location}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: ${datasource.url}
      username: ${datasource.username}
      password: ${datasource.password}
      connection-properties: config.decrypt=true;publickey=${datasource.publickey};password=${datasource.password}
      filter:
        config:
          enabled: true
      # 密码解密工具类地址
      password-callback: cn.senlin.jiaoyi.util.database.DbPasswordCallback
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

mybatis:
  # 对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapper/*.xml
  # 对应实体类的路径
  type-aliases-package: cn.senlin.jiaoyi
